---
- name: Add vars file
  include_vars: Debian-vars.yml

- name: Adding Jenkins apt repository key
  apt_key:
    url: "{{ jenkins_repo_key }}"
    state: present

- name: Adding Jenkins apt repository
  apt_repository:
    repo: "{{ jenkins_apt_repo }}"
    state: present
    update_cache: true

- name: Downloading specific Jenkins version
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_version }}_all.deb"
    dest: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
  when: jenkins_version is defined

- name: Installing specific version of Jenkins.
  apt:
    deb: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
    state: present
  when: jenkins_version is defined

- name: Ensure Jenkins is installed.
  apt:
    name: jenkins
    state: "{{ jenkins_package_state }}"







